import { SECONDARY_BACKGROUND_COLOR } from '../styles/theme';

export const SCHEDULE_TYPES = {
  CLASSES: 'CLASSES',
  EXAMS: 'EXAMS',
};

export const DEFAULT_COURSE_COLORS = [
  SECONDARY_BACKGROUND_COLOR,
  SECONDARY_BACKGROUND_COLOR,
  SECONDARY_BACKGROUND_COLOR,
  SECONDARY_BACKGROUND_COLOR,
  SECONDARY_BACKGROUND_COLOR,
];

export const SEMESTER = {
  F22: 'F22',
  W23: 'W23',
};

export const SEMESTER_TRANSLATION = {
  F22: 'Fall 2022',
  W23: 'Winter 2023',
};

export const SEMESTER_TRANSITIONS = {
  FORWARD: 'FORWARD',
  BACK: 'BACK',
};
